# Generated by Django 5.1.4 on 2024-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_of_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookimages/'),
        ),
    ]
